 INSERT INTO BOOKTYPE (BOOKTYPE_ID, NAME, DISCOUNT) VALUES (1, 'Fiction', 10);
 INSERT INTO BOOKTYPE (BOOKTYPE_ID, NAME, DISCOUNT) VALUES (2, 'Non-fiction', 2);

 INSERT INTO BOOKS (BOOK_ID, TITLE, DESCRIPTION, AUTHOR, ISBN, PRICE, BOOKTYPE_ID) VALUES (1, 'Book 1', 'Description 1', 'Author 1', 'ISBN-1', 100, 1);
 INSERT INTO BOOKS (BOOK_ID, TITLE, DESCRIPTION, AUTHOR, ISBN, PRICE, BOOKTYPE_ID) VALUES (2, 'Book 2', 'Description 2', 'Author 2', 'ISBN-2', 70, 2);
